<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SupportsCrossPlatform>true</SupportsCrossPlatform>
  </PropertyGroup>

  <Import Project="..\..\DnSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(DnSpyAssemblyCopyright)</Copyright>
    <Version>$(DnSpyAssemblyVersion)</Version>
    <InformationalVersion>$(DnSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\dnSpy.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\dnSpy.Contracts.Logic.Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>dnSpy.Contracts.Logic.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\dnSpy.Contracts.Logic.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>dnSpy.Contracts.Logic.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="$(DnlibVersion)" />
    <PackageReference Include="NuGet.Configuration" Version="$(NuGetVersion)" />
    <!-- TODO: HACK to resolve the version conflict of System.Collections.Immutable between NuGet.Configuration and Roslyn-->
    <PackageReference Include="System.Collections.Immutable" Version="$(DotNetPackageVersion)" />
  </ItemGroup>

</Project>
